### ISSUE TITLE
Spring Boot 2 compatibility

### ISSUE THREAD

**Issue by salaboy** [OpenFeign/feign-form#40]
Hi guys, 
Is there any plans to move this forward to Spring Boot 2? 
```
 <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.5.9.RELEASE</version>
  </parent>
```
?

**Comment by xxlabaza** [comment]
@Salaboy do you have any compatibility issues or something? If so - could you please provide some test example? 

From my side, I am pretty sure what it should work with SB2 fine

**Comment by Salaboy** [comment]
@xxlabaza thanks a lot for the response, I was wondering mostly because we added the dep, we needed to manage the dependency separately from Spring Boot 2 and when we start reviewing the poms here it highlighted the use of 1.5.9.RELEASE version. I don't know much of the internals, but it seemed to work just fine with SB 2, but we are not heavily testing, so we were wondering if there is a plan to test and update the parent to follow SB 2 release train.

**Comment by lewiskeifer** [comment]
I am having a similar issue.  One project running Spring 1.5 is working, but our other project running Spring 2.0 is not.
